spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3315/smc
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: 'classpath:db/migrations/changeLog.xml'

  data:
    rest:
      base-path: api

server:
  port: 8050
